<?php

namespace AmiDanseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DanseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DanseurRepository extends EntityRepository
{
}
