<?php

namespace AmiDanseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessorRepository extends EntityRepository
{
}
