AmiDanseBundle\Entity\Lesson:
    type: entity
    table: null
    repositoryClass: AmiDanseBundle\Repository\LessonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        danse:
            type: string
            length: '100'
        date:
            type: datetime
        level:
            type: string
            length: '100'
        schedule:
            type: time
        duration:
            type: time
        room:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
